// Data pool for the Compliment & Insult generator.
// Five tones, each with 50 compliments and 50 playful insults. Sentences are
// written in the second person ("You ...") so an optional recipient name can be
// prepended as "Alex, you ...". All insults are kept good-natured / banter-safe.

export interface Tone {
  id: string;
  label: string;
  /** Short blurb shown under the selector. */
  hint: string;
}

export const TONES: Tone[] = [
  { id: 'casual', label: 'Casual', hint: 'Everyday, friendly and easy-going.' },
  { id: 'formal', label: 'Formal', hint: 'Polished and professional.' },
  { id: 'poetic', label: 'Poetic', hint: 'Lyrical and a little dramatic.' },
  { id: 'shakespearean', label: 'Shakespearean', hint: 'Ye olde thees and thous.' },
  { id: 'savage', label: 'Savage', hint: 'Sharp, cheeky and over the top.' },
];

export const COMPLIMENTS: Record<string, string[]> = {
  casual: [
    'You have a knack for making people feel at ease.',
    'You are honestly just really easy to be around.',
    'You always know the right thing to say.',
    'You make even boring days feel a little brighter.',
    'You have great taste — no notes.',
    'You are the friend everyone wishes they had.',
    'You light up a group chat like nobody else.',
    'You give the best advice without being preachy.',
    'You are so much fun to hang out with.',
    'You have a laugh that is genuinely contagious.',
    'You show up when it matters, every time.',
    'You are impressively good at basically everything you try.',
    'You have a way of making people feel heard.',
    'You are the definition of a good hang.',
    'You always bring the good vibes.',
    'You are way funnier than you give yourself credit for.',
    'You make hard things look effortless.',
    'You have excellent taste in music.',
    'You are the calm in everyone else’s chaos.',
    'You remember the little things that matter to people.',
    'You are ridiculously easy to talk to.',
    'You have this warmth that just draws people in.',
    'You are the human equivalent of a sunny afternoon.',
    'You never make anyone feel left out.',
    'You are the one who keeps the whole crew together.',
    'You have a smile that could fix a bad day.',
    'You are so genuine it is honestly refreshing.',
    'You make ordinary moments feel special.',
    'You are the friend who always picks up the phone.',
    'You give the kind of hugs people remember.',
    'You are effortlessly cool without even trying.',
    'You have a heart the size of a house.',
    'You are the reason group photos actually turn out fun.',
    'You have great instincts about people.',
    'You are the best kind of trouble.',
    'You make everyone around you a little braver.',
    'You are surprisingly wise for how goofy you are.',
    'You have a gift for cheering people up.',
    'You are so thoughtful it catches people off guard.',
    'You are the most reliable person I know.',
    'You have a great eye for the little details.',
    'You are the human version of a warm blanket.',
    'You always find the silver lining.',
    'You are seriously talented and way too humble about it.',
    'You make people feel like the most interesting person in the room.',
    'You have the best comebacks, honestly.',
    'You are the friend who remembers the inside jokes.',
    'You are just a genuinely good person.',
    'You make the world feel a bit less heavy.',
    'You are exactly the energy this place needed.',
  ],
  formal: [
    'You bring a rare thoughtfulness to everything you do.',
    'You conduct yourself with remarkable grace under pressure.',
    'You have an exceptional eye for detail.',
    'You demonstrate integrity in the smallest of decisions.',
    'You possess a truly admirable work ethic.',
    'You articulate complex ideas with impressive clarity.',
    'You inspire confidence in everyone around you.',
    'You approach challenges with commendable composure.',
    'You have a gift for bringing out the best in others.',
    'You set a standard others genuinely aspire to.',
    'You handle responsibility with quiet excellence.',
    'You are unfailingly considerate of those around you.',
    'You bring both intelligence and warmth to any room.',
    'You have earned the respect you so clearly command.',
    'You listen with a rare and generous attention.',
    'You are a steadying presence in difficult moments.',
    'You show consistent good judgment.',
    'You elevate the quality of every conversation.',
    'You lead by example rather than by title.',
    'You are as principled as you are capable.',
    'You bring clarity to situations that others find confusing.',
    'You have a distinguished sense of professionalism.',
    'You treat everyone with genuine courtesy.',
    'You are refreshingly candid and always fair.',
    'You carry yourself with quiet, earned confidence.',
    'You have an admirable capacity for patience.',
    'You are trusted precisely because you have earned it.',
    'You approach your work with real craftsmanship.',
    'You are thoughtful in ways that others overlook.',
    'You bring calm authority to any undertaking.',
    'You are consistently dependable when it counts.',
    'You have a keen and discerning mind.',
    'You are gracious in both success and setback.',
    'You possess a wisdom well beyond the ordinary.',
    'You make thoughtful decisions with admirable resolve.',
    'You have a talent for putting others at ease.',
    'You represent the very best of your profession.',
    'You are as diligent as you are kind.',
    'You bring a welcome dignity to your work.',
    'You have an exceptional command of your craft.',
    'You are a model of poise and preparation.',
    'You show remarkable foresight in your planning.',
    'You are unfailingly gracious with your time.',
    'You have a truly generous spirit.',
    'You are the sort of person others quietly rely upon.',
    'You demonstrate leadership in the truest sense.',
    'You bring a rare balance of head and heart.',
    'You are held in the highest regard, and deservedly so.',
    'You approach every task with genuine care.',
    'You are, in every sense, a credit to those around you.',
  ],
  poetic: [
    'You carry a quiet light that others gather around.',
    'You are the pause between two lovely notes.',
    'You move through the world like a slow, kind sunrise.',
    'You are a chapter people are grateful to have read.',
    'You are the warmth a room forgets it was missing.',
    'You are a lighthouse for the people who lose their way.',
    'You are made of the same stuff as first snowfalls.',
    'You leave a little more beauty everywhere you go.',
    'You are the soft hour just before the stars.',
    'You are a melody the day hums without knowing.',
    'You are the calm after the storm decides to rest.',
    'You are the kind of good that outlasts the weather.',
    'You are a garden that blooms in other people’s winters.',
    'You are the last golden light of a long afternoon.',
    'You are a poem the world keeps trying to memorize.',
    'You are the tide that always finds its way home.',
    'You are a candle steady in every draft.',
    'You are the hush that makes music worth waiting for.',
    'You are the horizon someone was searching for.',
    'You are a fire that warms without ever burning.',
    'You are the gentle rain that makes everything grow.',
    'You are the constellation others steer their lives by.',
    'You are a river that carves canyons with patience alone.',
    'You are the open window on a stifling day.',
    'You are the color the sky forgets it can be.',
    'You are the story people return to for comfort.',
    'You are the first warm morning after a long cold.',
    'You are a bell that rings clear across the valley.',
    'You are the kind of beautiful that has nothing to prove.',
    'You are the still water that holds the whole moon.',
    'You are a spring the desert dreams about.',
    'You are the quiet strength of an ancient tree.',
    'You are the breath the world takes when it needs peace.',
    'You are a harbor for every restless heart.',
    'You are the light that makes the shadows kind.',
    'You are the promise the dawn keeps every day.',
    'You are the melody grief forgets to be sad to.',
    'You are the good the darkness cannot argue with.',
    'You are a hearth in the middle of a long night.',
    'You are the wildflower that grows where nothing should.',
    'You are the echo of every kind word ever spoken.',
    'You are the moment a held breath finally lets go.',
    'You are the soft place a weary world lands.',
    'You are the sunlight caught in an ordinary glass.',
    'You are the north star of every wandering evening.',
    'You are the season everyone secretly waits for.',
    'You are a small, stubborn miracle of a person.',
    'You are the warmth left in a cup long after the tea.',
    'You are the reason certain days are remembered fondly.',
    'You are, quite simply, someone the world is better for.',
  ],
  shakespearean: [
    'Thou art a rose among the common thorns of court.',
    'Thy kindness doth outshine the summer sun.',
    'Thou art as noble in heart as any crownèd king.',
    'Thy wit is sharper than a well-honed blade.',
    'Thou art a treasure richer than the deepest mine.',
    'Thy laughter is music fit for a royal hall.',
    'Thou art the fairest company in all the realm.',
    'Thy counsel is worth more than a chest of gold.',
    'Thou art a beacon in the darkest of nights.',
    'Thy grace would humble the proudest of lords.',
    'Thou art gentle as the morning dew upon the rose.',
    'Thy heart is truer than the north star itself.',
    'Thou art a marvel that poets would fain describe.',
    'Thy spirit is bolder than a lion of the field.',
    'Thou art as constant as the turning of the tide.',
    'Thy virtue shineth brighter than a thousand candles.',
    'Thou art the very picture of goodness made flesh.',
    'Thy presence doth make glad the heaviest of hearts.',
    'Thou art wiser than the greybeards of the senate.',
    'Thy soul is fairer than the fairest spring.',
    'Thou art a friend most rare in this false world.',
    'Thy goodness would move even the hardest stone.',
    'Thou art a jewel that no crown could contain.',
    'Thy honour standeth firm when others fall.',
    'Thou art the sweetest melody mine ears have known.',
    'Thy courage would shame the boldest of knights.',
    'Thou art more radiant than the harvest moon.',
    'Thy tongue speaketh only that which is just and kind.',
    'Thou art a garden in the winter of our days.',
    'Thy loyalty is a fortress none may breach.',
    'Thou art blessed with a wit both quick and warm.',
    'Thy company is a feast for the weary traveller.',
    'Thou art fairer than a summer’s longest day.',
    'Thy heart doth beat with uncommon nobility.',
    'Thou art a light that no tempest can extinguish.',
    'Thy generosity would fill the coffers of a king.',
    'Thou art the truest mirror of a gentle soul.',
    'Thy patience is a virtue few mortals possess.',
    'Thou art a comfort dearer than the softest down.',
    'Thy laughter chaseth away the gloom of care.',
    'Thou art a star by which the lost may steer.',
    'Thy kindness is a balm to every wounded heart.',
    'Thou art more precious than the crown jewels themselves.',
    'Thy friendship is a bond that time cannot undo.',
    'Thou art the finest flower in the garden of the world.',
    'Thy goodness is a song the angels envy.',
    'Thou art as dear to me as breath itself.',
    'Thy noble bearing doth grace this humble place.',
    'Thou art a wonder the ages shall remember.',
    'Thou art, in sooth, the very best of us all.',
  ],
  savage: [
    'You are unfairly good-looking and it is genuinely rude.',
    'You are so talented it is honestly a little annoying.',
    'You make the rest of us look bad, and we love you for it.',
    'You are ridiculously charming and you know it.',
    'You walk in and everyone else may as well go home.',
    'You are the main character and the rest of us are extras.',
    'You are proof that some people just get all the good genes.',
    'You are so cool it should be studied by scientists.',
    'You are the best in the room, and it is not even close.',
    'You are so impressive it is borderline showing off.',
    'You could win an argument against a brick wall.',
    'You are wittier than everyone here combined.',
    'You are that good, and I hate that you know it.',
    'You are the reason “effortless” became a compliment.',
    'You make genius look casual, and it is infuriating.',
    'You are too smart for your own good, honestly.',
    'You are the whole package and the wrapping paper too.',
    'You are so put-together it is almost suspicious.',
    'You are a legend and refuse to act like one.',
    'You are the standard everyone else is failing to meet.',
    'You are dangerously likeable, it should be regulated.',
    'You are the best thing to happen to this group, no contest.',
    'You could sell sand in a desert and they’d thank you.',
    'You are so sharp you could cut glass with a comeback.',
    'You are the upgrade everyone else wishes they had.',
    'You are annoyingly perfect and I refuse to elaborate.',
    'You are the reason the bar is set impossibly high.',
    'You are so good it feels like cheating.',
    'You are the plot twist nobody deserved but everybody needed.',
    'You are too iconic for this small town energy.',
    'You are the funniest person here and you barely try.',
    'You are unreasonably talented for one human being.',
    'You are the kind of great that makes people nervous.',
    'You are the peak, everyone else is base camp.',
    'You are so gifted it is basically unfair to the rest of us.',
    'You are the reason “goals” is a word.',
    'You are effortlessly better at this than people who practice.',
    'You are the blueprint and everyone else is a rough draft.',
    'You are so quick-witted it should come with a warning.',
    'You are the highlight reel while we are all bloopers.',
    'You are almost too good, and that is a real problem for us.',
    'You are the one they’ll be talking about for years.',
    'You are so magnetic it is practically a superpower.',
    'You are the exception to every rule about ordinary people.',
    'You are so brilliant it is a public menace.',
    'You are the reason the phrase “out of your league” exists.',
    'You are frankly overqualified to be this humble.',
    'You are the kind of amazing that ruins the average for everyone.',
    'You are showing off just by existing, and it’s working.',
    'You are, and I say this with love, absurdly great.',
  ],
};

export const INSULTS: Record<string, string[]> = {
  casual: [
    'You have the charisma of a damp sock.',
    'You are proof that even autocorrect gives up sometimes.',
    'You bring so much joy — mostly when you leave.',
    'You have a face made for radio.',
    'You are as sharp as a bowling ball.',
    'You are the reason the instructions say “do not eat.”',
    'You are about as useful as a chocolate teapot.',
    'You could trip over a cordless phone.',
    'You are running on last week’s battery.',
    'You are the human version of a participation trophy.',
    'You have two brain cells and they are both fighting.',
    'You are as deep as a puddle in July.',
    'You are the plot hole in everyone else’s good day.',
    'You are the reason shampoo has directions.',
    'You are a few fries short of a Happy Meal.',
    'You are the software update nobody asked for.',
    'You are living proof that talk is cheap.',
    'You are about as coordinated as a newborn giraffe.',
    'You are the group project everyone secretly dreads.',
    'You are as reliable as a chocolate fireguard.',
    'You are the reason mirrors look away.',
    'You are the buffering icon of human beings.',
    'You are one crayon short of a full box.',
    'You are the ick, in person.',
    'You are about as bright as a black marker.',
    'You are the reason the gene pool needs a lifeguard.',
    'You have the depth of a kiddie pool.',
    'You are running Windows Vista on a good day.',
    'You could get lost in a straight hallway.',
    'You are the human embodiment of a typo.',
    'You are as fun as a flat tire in the rain.',
    'You are the reason “read the room” exists.',
    'You are proof that not all superheroes have powers, some just have opinions.',
    'You are the loading screen that never finishes.',
    'You are as quick as dial-up internet.',
    'You are the extra button that comes with the shirt.',
    'You are the awkward silence made flesh.',
    'You are one bad decision away from a cautionary tale.',
    'You are the reason “bless your heart” was invented.',
    'You have the personality of unseasoned tofu.',
    'You are the human equivalent of a Monday.',
    'You are as subtle as a car alarm.',
    'You are the pop-up ad of conversations.',
    'You are living life on airplane mode.',
    'You are the reason patience was invented.',
    'You are as useful as a screen door on a submarine.',
    'You are the “skip intro” button we all wish existed for you.',
    'You are running on 1% and refusing to charge.',
    'You are the low-battery warning of people.',
    'You are, and I mean this gently, a whole lot of nope.',
  ],
  formal: [
    'You possess a truly remarkable talent for underachievement.',
    'You have elevated mediocrity to something of an art form.',
    'You bring a certain confidence rarely justified by results.',
    'You demonstrate an admirable commitment to missing the point.',
    'You are consistently underwhelming with impressive reliability.',
    'You have a gift for making simple tasks needlessly complicated.',
    'You approach every good idea with commendable resistance.',
    'You are, in the finest tradition, all hat and no cattle.',
    'You articulate nonsense with genuinely striking conviction.',
    'You have mastered the appearance of effort without its substance.',
    'You are a cautionary tale delivered with excellent posture.',
    'You bring meetings to a standstill with rare efficiency.',
    'You have a distinguished record of learning nothing at all.',
    'You are proof that confidence and competence rarely travel together.',
    'You conduct yourself with the poise of someone entirely mistaken.',
    'You have a singular talent for stating the obvious at length.',
    'You are reliably present and reliably unhelpful.',
    'You possess opinions in inverse proportion to your knowledge.',
    'You have refined procrastination into a personal philosophy.',
    'You are the living argument for a second opinion.',
    'You bring a rare gift for turning solutions into problems.',
    'You demonstrate leadership in precisely the wrong direction.',
    'You are exhaustively thorough about all the wrong details.',
    'You have an unerring instinct for the least useful contribution.',
    'You are as decisive as a coin that lands on its edge.',
    'You have perfected the art of being busy and useless.',
    'You bring the enthusiasm of a professional and the results of an amateur.',
    'You are a masterclass in how not to proceed.',
    'You have a talent for confidence untroubled by facts.',
    'You are consistently the weakest link, and admirably punctual about it.',
    'You approach feedback with the openness of a locked vault.',
    'You have turned excuses into a respectable second career.',
    'You are the meeting that could have been an email.',
    'You possess the rare ability to complicate a coin flip.',
    'You are diligently working below your own low bar.',
    'You have an exceptional gift for missing deadlines gracefully.',
    'You bring a scholar’s energy to entirely trivial matters.',
    'You are, in every measurable sense, a work still in progress.',
    'You have a distinguished talent for confident wrongness.',
    'You are the footnote no one needed in an already long report.',
    'You demonstrate a truly enduring resistance to improvement.',
    'You approach responsibility the way water approaches a duck.',
    'You have made a fine art of being almost helpful.',
    'You are impressively committed to the path of least insight.',
    'You possess the tactical genius of a surrendered chess piece.',
    'You are as sharp as the back of a spoon.',
    'You bring a curator’s eye to your own poor decisions.',
    'You have earned your reputation entirely by lowering expectations.',
    'You are, with all due respect, a formidable disappointment.',
    'You are the very model of a modern minor letdown.',
  ],
  poetic: [
    'You are the fog that lingers when everyone wants the sun.',
    'You are a candle that gutters at the first hint of wind.',
    'You are the winter that overstays its welcome.',
    'You are a song that forgets its own melody.',
    'You are the puddle that ruins an otherwise fine morning.',
    'You are a cloud with no rain and no shade.',
    'You are the echo of a joke nobody laughed at.',
    'You are the draft under every warm door.',
    'You are a lighthouse pointed firmly at the rocks.',
    'You are the last cold coffee of a long day.',
    'You are the pause that kills a good conversation.',
    'You are a garden that grows only weeds.',
    'You are the storm cloud at a summer picnic.',
    'You are a bell that rings only when no one listens.',
    'You are the fine print on a broken promise.',
    'You are the wrong turn that adds an hour to the trip.',
    'You are a mirror that flatters no one, least of all itself.',
    'You are the gray hour that refuses to become dawn.',
    'You are the moth that mistakes the exit for the light.',
    'You are a river that runs only downhill and dry.',
    'You are the ache that arrives before the weather does.',
    'You are the crumb at the bottom of an empty bag.',
    'You are a firework that fizzles on the ground.',
    'You are the tide that takes but never brings.',
    'You are the flat note in an otherwise lovely hymn.',
    'You are the frost that finds the tenderest bud.',
    'You are a map that leads only in circles.',
    'You are the silence after a bad idea.',
    'You are the wilted flower in an otherwise fine bouquet.',
    'You are the leak the roof forgot to mention.',
    'You are a lantern with no oil and grand ambitions.',
    'You are the chapter readers politely skip.',
    'You are the shadow that arrives before the sun sets.',
    'You are a well that echoes but holds no water.',
    'You are the cold spot in an otherwise warm bed.',
    'You are the wind that blows out every candle it meets.',
    'You are a compass that points only at itself.',
    'You are the smudge on an otherwise perfect window.',
    'You are the delay on an already late train.',
    'You are a harbor that leaks every ship it holds.',
    'You are the itch no season can soothe.',
    'You are the cloud that follows only the picnics.',
    'You are the sour note the choir tries to bury.',
    'You are the ash where a fire should have been.',
    'You are the fine day that a single word ruins.',
    'You are a season nobody circled on the calendar.',
    'You are the moon on the one night everyone wanted stars.',
    'You are the drizzle that outlasts the parade.',
    'You are the ending a good story did not deserve.',
    'You are, in gentle truth, an acquired and rarely acquired taste.',
  ],
  shakespearean: [
    'Thou art a boil, a plague-sore, a most toad-spotted knave!',
    'Thou clay-brained guts, thou knotty-pated fool!',
    'Thou art a spongy, onion-eyed measle!',
    'Thou reeky, rump-fed haggard, get thee gone!',
    'Thou art a very ragged wart upon the face of wit.',
    'Thou beslubbering, beetle-headed flap-dragon!',
    'Thou art as loathsome as a toad in a maiden’s slipper.',
    'Thou froward, fen-sucked foot-licker!',
    'Thou art a most notable coward, an infinite and endless liar.',
    'Thou gleeking, half-faced hedge-pig!',
    'Thou art duller than a great thaw.',
    'Thou puking, tickle-brained pignut!',
    'Thou art a fusty nut with no kernel.',
    'Thou villainous, dread-bolted lout!',
    'Thou art the very rats of the earth made flesh.',
    'Thou artless, base-court apple-john!',
    'Thou art a wretch whose natural gifts were poor indeed.',
    'Thou mewling, milk-livered maggot-pie!',
    'Thou art a boil upon the buttock of the realm.',
    'Thou goatish, ill-nurtured miscreant!',
    'Thou art fouler than the foulest fen in Christendom.',
    'Thou paunchy, plume-plucked pumpion!',
    'Thou art an ass-head and a coxcomb and a knave.',
    'Thou surly, sheep-biting scut!',
    'Thou art a rank weed in an otherwise fair meadow.',
    'Thou pribbling, pox-marked pignut!',
    'Thou art less use than a broken sword to a beggar.',
    'Thou spleeny, swag-bellied strumpet of folly!',
    'Thou art the very abstract of all faults.',
    'Thou weedy, weather-bitten wagtail!',
    'Thou art a most unwholesome fen of stinking weeds.',
    'Thou craven, clapper-clawed clotpole!',
    'Thou art a jolthead with less wit than a post.',
    'Thou dankish, dizzy-eyed dewberry!',
    'Thou art the scurviest knave in all the land.',
    'Thou loggerheaded, lily-livered lout!',
    'Thou art a whey-faced, tallow-catch of a coward.',
    'Thou vain, venomed varlet of the gutter!',
    'Thou art more foolish than a jester’s bell.',
    'Thou errant, elf-skinned earwig!',
    'Thou art a scab, a scurvy politician’s echo.',
    'Thou frothy, fool-born flax-wench!',
    'Thou art the rankest compound of villainy that ever breathed.',
    'Thou mangled, motley-minded moldwarp!',
    'Thou art but a walking argument for silence.',
    'Thou bootless, beef-witted barnacle!',
    'Thou art a knave, a rascal, an eater of broken meats.',
    'Thou puny, plume-brained puttock!',
    'Thou art a most pitiful ambition of a man.',
    'Thou art, in sooth, the very lees and dregs of wit.',
  ],
  savage: [
    'You are the reason the group chat has a “do not add” list.',
    'You have the emotional range of a parking meter.',
    'You are what happens when confidence skips leg day and brain day.',
    'You are living proof that evolution can take a lunch break.',
    'You are the human embodiment of a dropped call.',
    'You are so basic they named a search bar after you.',
    'You have the personality of a expired coupon.',
    'You are the plot twist nobody wanted and everyone saw coming.',
    'You are the reason “return to sender” exists.',
    'You are the free trial nobody upgraded.',
    'You bring nothing to the table and eat everyone else’s share.',
    'You are the spam folder of human beings.',
    'You are a cautionary tale with great lighting.',
    'You are the reason the mute button was invented.',
    'You are the discount version of someone forgettable.',
    'You have the depth of a phone screen and half the battery.',
    'You are a walking “skip this part” button.',
    'You are the reason the internet has terms and conditions.',
    'You are as memorable as a hold-music jingle.',
    'You are the reason “new phone, who dis” was written.',
    'You peaked at a birthday party in third grade.',
    'You are the software bug that customer support ignores.',
    'You are the group project that dragged everyone’s grade down.',
    'You are a solid case for reading the room and then leaving it.',
    'You are what the algorithm serves when it gives up.',
    'You are the expired milk of personalities.',
    'You are the “are you still watching” prompt of people.',
    'You are the reason auto-reply was invented.',
    'You are a live demonstration of secondhand embarrassment.',
    'You are the human version of a captcha nobody passes.',
    'You are the discount aisle of takes and opinions.',
    'You are the reason the block button gets a workout.',
    'You are the “this could have been an email” of humans.',
    'You are the participation certificate life keeps trying to hand out.',
    'You are the reason instructions come with pictures.',
    'You are a masterclass in how to lower a bar already on the floor.',
    'You are the lag between everyone’s patience and yours.',
    'You are the “decline all cookies” of conversations.',
    'You are the reason there is a warning on the hairdryer.',
    'You are the sequel nobody greenlit.',
    'You have all the impact of a soft handshake.',
    'You are the reason the phrase “bless it and move on” exists.',
    'You are a strong argument for reading before you speak.',
    'You are the buffering wheel of everyone’s good time.',
    'You are the reason group photos get cropped.',
    'You are the “no thanks” that walks like a person.',
    'You are the reason the fire alarm has a test button.',
    'You are a whole personality built out of leftover opinions.',
    'You are, and I say this with a straight face, a lot to overcome.',
    'You are the reason the delete key wears out first.',
  ],
};

// Self-check: every tone has exactly 50 of each, and ids line up.
export function _selfCheck(): void {
  for (const t of TONES) {
    const c = COMPLIMENTS[t.id]?.length ?? 0;
    const i = INSULTS[t.id]?.length ?? 0;
    if (c !== 50 || i !== 50) {
      throw new Error(`tone ${t.id}: ${c} compliments, ${i} insults (want 50/50)`);
    }
  }
}
