// Country list + Indian state/UT list shared by the document generators'
// structured address blocks. India leads the country list because the GST
// fields (GSTIN, state) are India-centric; the state dropdown only applies
// when India is the selected country.

export const COUNTRIES: string[] = [
  'India',
  'United States',
  'United Kingdom',
  'United Arab Emirates',
  'Australia',
  'Canada',
  'Singapore',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
  'New Zealand',
  'South Africa',
  'Japan',
  'China',
  'Hong Kong',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Philippines',
  'Vietnam',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Pakistan',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Spain',
  'Italy',
  'Portugal',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Belgium',
  'Austria',
  'Poland',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'Nigeria',
  'Kenya',
  'Egypt',
  'Israel',
  'Turkey',
  'South Korea',
];

// The 28 states + 8 union territories of India, alphabetical — matches the
// order Razorpay's generator uses (Andaman and Nicobar Islands first).
export const INDIA_STATES: string[] = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];
