

export const WORDS5 = (
  'about above abuse actor acute admit adopt adult after again agent agree ahead ' +
  'alarm album alert alike alive allow alone along aloud alpha altar alter amber ' +
  'amend among angel anger angle angry ankle apart apple apply arena argue arise ' +
  'armor aroma array arrow aside asset audio audit avoid awake award aware awful ' +
  'bacon badge baker basic basin batch beach beard beast began begin being belly ' +
  'below bench berry birth black blade blame blank blast blaze bleed blend bless ' +
  'blind block blood bloom blown blues board boast bonus boost booth bound brace ' +
  'brain brake brand brave bread break breed brick bride brief bring broad broke ' +
  'brook broom brown brush build built bunch burst cabin cable cache camel canal ' +
  'candy canon cargo carol carry carve catch cause cease chain chair chalk champ ' +
  'chaos charm chart chase cheap cheat check cheek cheer chess chest chief child ' +
  'chill china chose chunk civic civil claim clamp clash class clean clear clerk ' +
  'click cliff climb cling cloak clock close cloth cloud clown clubs coach coast ' +
  'cocoa colon color comet comic coral corps couch cough could count court cover ' +
  'crack craft crane crash crawl crazy cream creek crept crest crime crisp cross ' +
  'crowd crown crude cruel crumb crush crust cubic curve cycle daily dairy dance ' +
  'dated dealt death debit debut decay decor delay delta dense depot depth devil ' +
  'diary dirty ditch diver dizzy dodge doing donor doubt dough dozen draft drain ' +
  'drama drank drawn dread dream dress dried drift drill drink drive drone drove ' +
  'drown drums drunk dusty dwarf dwell eager eagle early earth easel eaten ebony ' +
  'edict eerie eight elbow elder elect elite elope empty enact ended enemy enjoy ' +
  'enter entry equal equip erase error essay ethic evade event every evict evoke ' +
  'exact exams excel exert exile exist extra fable faced facts faery faint fairy ' +
  'faith false fancy fatal fault favor feast fence ferry fetch fever fewer fiber ' +
  'field fiend fifth fifty fight final finch first fixed flag flair flame flank ' +
  'flash flask fleet flesh flick fling flint float flock flood floor flora floss ' +
  'flour flown fluid flung flush focal focus force forge forgo forth forty forum ' +
  'found frame frank fraud fresh fried frill frock front frost frown fruit fully ' +
  'fungi funny gauge gaunt gauze gecko genre ghost giant given giver glade gland ' +
  'glare glass gleam glide globe gloom glory gloss glove going grace grade grain ' +
  'grand grant grape graph grasp grass grave gravy graze great greed green greet ' +
  'grief grill grime grind groan groin groom gross group grove growl grown gruff ' +
  'guard guess guest guide guild guilt guise habit hairy handy happy hardy harsh ' +
  'haste hatch haunt haven havoc hazel heads heart heavy hedge hefty hello hence ' +
  'herbs hilly hinge hippo hobby hoist honey honor horde horse hotel hound house ' +
  'hover human humid humor hunch hurry husky hymns ideal idiom idiot igloo image ' +
  'imply inbox incur index inept infer inlet inner input intro ionic irate irony ' +
  'issue ivory jaunt jazzy jeans jelly jewel joint joker jolly joust judge juice ' +
  'jumbo juror kayak kebab ketch khaki kinky kiosk kitty knack kneel knelt knife ' +
  'knock known koala label labor laden lance lapel large larva laser latch later ' +
  'lathe layer leach leafy leaky leant leapt learn lease leash least leave ledge ' +
  'legal lemon level lever light liked limbo limit lined liner lingo lipid liver ' +
  'llama loath lobby local locus lodge lofty logic login loose lorry loser lotus ' +
  'lough lousy loved lover lower loyal lucky lunar lunch lunge lurch lyric macro ' +
  'madam magic major maker mango mania manor maple march marry marsh mason match ' +
  'mayor meant medal media medic melon mercy merge merit merry metal meter micro ' +
  'midst might mimic mince mined miner minor minus mirth miser mixed mocha model ' +
  'moist molar money month moody moose moral morph mossy motel motor motto mould ' +
  'mound mount mourn mouse mouth mover movie mower muddy mummy mural music musky ' +
  'nadir naive naked nasal nasty naval navel needy nerve never newly niche niece ' +
  'night ninja ninth noble nobly noise noisy nomad north notch noted novel nudge ' +
  'nurse nutty nylon oasis occur ocean offer often olive onion onset opera orbit ' +
  'order organ ought ounce outdo outer ovary overt owing owner ozone paddy pagan ' +
  'paint panel panic paper parka party pasta paste patch patio pause peace peach ' +
  'pearl pedal penny perch peril petal petty phase phone photo piano piece piety ' +
  'piggy pilot pinch pixel pizza place plaid plain plane plank plant plate plaza ' +
  'plead pleat plied pluck plumb plume plump plush poems point poise poker polar ' +
  'poppy porch posit pouch pound power press price pride prime primo print prior ' +
  'prism privy prize probe promo prone proof props proud prove prowl proxy prune ' +
  'psalm pulse punch pupil puppy puree purge purse pushy quack quail quake qualm ' +
  'quart queen query quest queue quick quiet quill quilt quirk quite quota quote ' +
  'rabbi radar radio rainy raise rally ranch range rapid rarer raspy ratio ratty ' +
  'raven reach react ready realm rebel refer reign relax relay relic remit renal ' +
  'renew repay repel reply resin retro rhino rhyme rider ridge rifle right rigid ' +
  'rinse ripen risen risky rival river roach roast robin robot rocky rodeo rogue ' +
  'roman rotor rouge rough round route rover royal ruddy ruler rumor rural rusty ' +
  'sadly saint salad salon salsa salty salve sandy satin sauce saucy sauna savor ' +
  'scald scale scalp scaly scamp scant scare scarf scene scent scoff scold scone ' +
  'scoop scope score scorn scour scout scowl scrap scrub scuba seize sedan sepia ' +
  'serve setup seven sever shade shady shaft shake shaky shale shall shame shape ' +
  'share shark sharp shave shawl sheep sheer sheet shelf shell shied shift shine ' +
  'shiny shirt shock shone shook shoot shore short shout shove shown showy shrub ' +
  'shrug shuck shunt shush shyly siege sight sigma silky silly since sinew singe ' +
  'siren sixth sixty skate skier skill skimp skirt skulk skull skunk slack slain ' +
  'slang slant slash slate slave sleek sleep sleet slept slice slick slide slime ' +
  'sling slink slope slosh sloth slump slung slurp slush small smart smash smear ' +
  'smell smelt smile smirk smite smock smoke smoky snack snail snake snaky snare ' +
  'snarl sneak sneer snide sniff snipe snoop snore snort snout snowy snuck snuff ' +
  'sober soggy solar solid solve sonar sonic sooth sorry sound south space spade ' +
  'spank spare spark spasm spawn speak spear speck speed spell spend spent sperm ' +
  'spice spicy spied spike spiky spill spilt spine spiny spire spite splat split ' +
  'spoil spoke spoof spook spool spoon sport spout spray spree sprig spurn spurt ' +
  'squad squat squid stack staff stage staid stain stair stake stale stalk stall ' +
  'stamp stand stank stare stark start stash state stave stead steak steal steam ' +
  'steel steep steer stein stern stick stiff still stilt sting stink stint stock ' +
  'stoic stoke stole stomp stone stony stood stool stoop store stork storm story ' +
  'stout stove strap straw stray strip strut stuck study stuff stump stung stunt ' +
  'style suave sugar suite sulky sunny super surge sushi swami swamp swarm swash ' +
  'swath swear sweat sweep sweet swell swept swift swill swine swing swirl swish ' +
  'swoon swoop sword swore sworn swung syrup table taboo tacit tacky taffy taken ' +
  'tally tango tangy taper tapir tardy taste tasty taunt tawny teach tease teddy ' +
  'teeth tempo tenor tense tepid terse testy thank theft their theme there these ' +
  'thick thief thigh thing think third thong thorn those three threw throb throw ' +
  'thumb thump tiara tibia tidal tiger tight tilde timer timid tipsy titan tithe ' +
  'title toast today token tonal tonic tooth topaz topic torch torso total totem ' +
  'touch tough towel tower toxic toxin trace track tract trade trail train trait ' +
  'tramp trash tread treat trend triad trial tribe trick tried tripe trite troll ' +
  'troop trope trout trove truce truck truly trump trunk trust truth tulip tumor ' +
  'tunic turbo tutor twang tweak tweed tweet twice twine twirl twist tying udder ' +
  'ulcer ultra uncle under undue unfit unify union unite unity unlit unmet until ' +
  'unwed unzip upper upset urban urged usage usher using usual usurp utile utter ' +
  'vague valet valid value valve vapor vault vaunt vegan venom venue verge verse ' +
  'vicar video vigil vigor villa vinyl viola viper viral virus visit visor vista ' +
  'vital vivid vocal vodka vogue voice voila vomit voter vouch vowel wacky wafer ' +
  'wagon waist waive waltz waney waste watch water waver waxen weary weave wedge ' +
  'weedy weigh weird whack whale wharf wheat wheel whelp where which whiff while ' +
  'whine whiny whirl whisk white whole whoop whose widen wider widow width wield ' +
  'wight wince winch windy wiped wired wiser witch witty woken woman women woody ' +
  'wooer wooly world worry worse worst worth would wound woven wrack wrath wreak ' +
  'wreck wrest wring wrist write wrong wrote wrung yacht yearn yeast yield yodel ' +
  'young yours youth zebra zesty zonal'
).split(/\s+/).filter((w) => /^[a-z]{5}$/.test(w));

export const WORDS5_SET = new Set(WORDS5);
